name: Windows Build

on:
  push:
    branches:
      - release/9.0
  pull_request:
    branches:
      - release/9.0

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v7
      with:
        ref: 'release/9.0'
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          diffutils
          make
          nasm
          yasm
        path-type: inherit
        update: true

    - name: Setup MSYS2
      shell: msys2 {0}
      run: mv /usr/bin/link.exe /usr/bin/link.exe.bak
        
    - name: Configure library
      shell: msys2 {0}
      env:
        UPLOAD_FOLDER: ${{github.workspace}}\upload
      run: |
        CC=cl
        ./configure \
        --arch=x86_64 \
        --target-os=win64 \
        --toolchain=msvc \
        --prefix=$UPLOAD_FOLDER \
        --enable-gpl \
        --disable-static \
        --enable-shared \
        --disable-all \
        --disable-everything \
        --disable-doc \
        --enable-avcodec \
        --enable-avformat \
        --enable-avutil \
        --enable-swresample \
        --enable-w32threads \
        --disable-network \
        --enable-error-resilience \
        --enable-decoder=h264,hevc,vvc,av1,aac,ac3,dca,eac3 \
        --enable-demuxer=h264,hevc,vvc,av1,aac,ac3,dca,eac3 \
        --enable-parsers \
        --enable-protocols \
        --disable-decoder=libdav1d \
        --enable-d3d11va \
        --enable-d3d12va \
        --enable-dxva2 \
        --enable-bsfs \
        --disable-iconv \
        --disable-schannel \
        --disable-zlib \
        --enable-debug

    - name: Build library
      shell: msys2 {0}
      run: make

    - name: Install library
      shell: msys2 {0}
      run: make install
      
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: Windows-artifact
        path: ${{github.workspace}}/upload
        if-no-files-found: ignore
        retention-days: 0
